export const data =[
    {key:"Poker",value:"Poker"},
    {key:"Action",value:"Action"},
    {key:"safe-avoid",value:"éviter en toute sécurité"},
    {key:"Quiz Game",value:"Jeu-questionnaire"},
    {key:"Pops Billiards",value:"Pops Billiards"},
    {key:"Math Rush",value:"Ruée vers les mathématiques"},
    {key:"Lucky Wheels",value:"Roues chanceuses"},
    {key:"Jigsaw Puzzle",value:"Puzzle"},
    {key:"Ice Cream Memory",value:"Mémoire de crème glacée"},
    {key:"Hangman",value:"Bourreau"},
    {key:"Nukkad Cricket",value:"Cricket Nukkad"},
    {key:"Foodie match",value:"Match gourmand"},
    {key:"Bubble",value:"Bulle"},
    {key:"Dark Village",value:"Village sombre"},
    {key:"Ghost-Dropper",value:"Ghost-Dropper"},
    {key:"Piggy Roll",value:"Rouleau de cochon"},
    {key:"Rail Rush",value:"Ruée ferroviaire"},
    {key:"NeonPath",value:"Chemin Néon"},
    {key:"Terror-Shooter",value:"Terreur-Shooter"},
    {key:"Clash of battles",value:"Choc des batailles"},
    {key:"Rose Dash",value:"Rose Dash"},
    {key:"Air Warfare",value:"Guerre aérienne"},
    {key:"Helicopter Contro",value:"Contrôle d'hélicoptère"},
    {key:"Adventure",value:"Aventure"},
    {key:"Super Cowboy Run",value:"Super course de cowboy"},
    {key:"LittleDinoAdventureReturns",value:"Le retour de LittleDinoAdventure"},
    {key:"Chimney-Port",value:"Cheminée-Port"},
    {key:"christmas adventure",value:"aventure de Noël"},
    {key:"SuDoKu",value:"SuDoKu"},
    {key:"Christmas Panda Run",value:"Course de panda de Noël"},
    {key:"Tetris Cube",value:"Cube Tétris"},
    {key:"Dragon Jump",value:"Saut du dragon"},
    {key:"Duck Shooter",value:"Tireur de canard"},
    {key:"Flapcat Steampunk",value:"Flapcat Steampunk"},
    {key:"Shoot Robbers",value:"Tirer sur les voleurs"},
    {key:"shooting gallery",value:"galerie de tir"},
    {key:"Gold Miner",value:"Mineur d'or"},
    {key:"Stick Panda",value:"Bâton Panda"},
    {key:"Wood Slide",value:"Toboggan en bois"},
    {key:"BubbleBoostRush",value:"BubbleBoostRush"},
    {key:"Charly Bird",value:"Charly Oiseau"},
    {key:"Ninja UpDown",value:"Ninja en haut en bas"},
    {key:"Reverse Gravity",value:"Gravité inversée"},
    {key:"Santa Run",value:"Course du Père Noël"},
    {key:"Mad Scientist",value:"Savant fou"},
    {key:"Puzzle",value:"Casse-tete"},
    {key:"Happy haloween",value:"Joyeux Halloween"},
    {key:"Fruity snake",value:"Serpent fruité"},
    {key:"Funny",value:"Drôle"},
    {key:"Aliens Memory",value:"Mémoire des extraterrestres"},
    {key:"Panic Drop",value:"Chute de panique"},
    {key:"ranger vs zombies",value:"rangers contre zombies"},
    {key:"Road Racer",value:"Coureur sur route"},
    {key:"Robber Run",value:"Course de voleurs"},
    {key:"Scary Run",value:"Course effrayante"},
    {key:"Racing",value:"Courses"},
    {key:"Crazy Car",value:"Voiture folle"},
    {key:"Fighter Aircraft",value:"Avion de chasse"},
    {key:"Goof Runner",value:"Coureur maladroit"},
    {key:"Great Air Battles",value:"Grandes batailles aériennes"},
    {key:"Animal Crush",value:"Écrasement d'animaux"},
    {key:"Ninja Run",value:"Course Ninja"},
    {key:"samup",value:"Samup"},
    {key:"Moto Traffic Rider",value:"Cavalier de la circulation moto"},
    {key:"Traffic command",value:"Commandement de la circulation"},
    {key:"Kids",value:"Enfants"},
    {key:"Puzzle for kids",value:"Puzzle for Enfants"},
    {key:"Find a Pair Animals",value:"Trouver une paire d'animaux"},
    {key:"Sports",value:"Sportif"},
    {key:"Chess Tower",value:"Tour d'échecs"},
    {key:"Dices jump",value:"Les dés sautent"},
    {key:"Bubble Town",value:"Ville bulle"},
    {key:"Escape",value:"S'échapper"},
    {key:"Pinball Rush",value:"Ruée vers le flipper"},
    {key:"Free Kick Penalty",value:"Coup franc"},
    {key:"Penalty Shootout",value:"Tirs au but"},
    {key:"Boom Baseball",value:"Boum Baseball"},
    {key:"Blocker",value:"Bloqueur"},
    {key:"Coloring Book For Kids",value:"Livre de coloriage pour les enfants"},
    {key:"Cat and Ghosts",value:"Chat et fantômes"},
    {key:"Arcade",value:"Arcade"},
    {key:"Pool 8 Ball",value:"Piscine 8 balles"},
    {key:"Gold miner",value:"Mineur d'or"},
    {key:"Stack Jump",value:"Saut de pile"},
    {key:"Handless Millionaire",value:"Millionnaire sans mains"},
    {key:"Angry cat school",value:"L'école des chats en colère"},
    {key:"Funny",value:"Drôle"},
    {key:"Robber Run",value:"Course de voleurs"},
    {key:"Circle Traffic",value:"Circulation circulaire"},
    {key:"Christmas Panda Run",value:"La course des pandas de Noël"},
    {key:"Extreme Sea Winner",value:"Vainqueur de la mer extrême"},
    {key:"shooting gallery",value:"stand de tir"},
    {key:"Math Rush",value:"Ruée vers les mathématiques"},
    {key:"Pops Billiards",value:"Pops Billiards"},
    {key:"shooting gallery",value:"stand de tir"},
    {key:"Gold Miner",value:"Mineur d'or"},
    {key:"christmas adventure",value:"aventure de Noël"},
    {key:"Ghost-Dropper",value:"Ghost-Dropper"},
    {key:"Charly Bird",value:"Charly Oiseau"},
    {key:"Stick Panda",value:"Bâton Panda"},
    {key:"BubbleBoostRush",value:"BubbleBoostRush"},
    {key:"Panic Drop",value:"Chute de panique"},
    {key:"Goof Runner",value:"Coureur maladroit"},
    
]